server:
  port: 6666
  servlet:
    context-path: /face/api

# face-api相关配置
face:
  api:
    app-id: 15633265
    api-key: mc9gdDrIAod42j2fhRBTsp3W
    secret-key: xiwRuedmcBLz0nWfIwWpdqrUXmoFlQzd
    group-id: test

